### ISSUE TITLE
Implement global registry + code-genned registration in the external_module.go template

### ISSUE THREAD

**Issue by matt2e** [block/ftl#1457]
We discussed this in the daily sync and there are a couple of limitations with the current approach:

1. The type registry is effectively static for the lifetime of a module's execution, but the registry is dynamically constructed and requires a `context.Context` to use.
2. Related to 1, this implies that it cannot be used by methods that don't pass a context around, including the stdlib's `encoding/json`.
3. Currently the registry is only constructed in the generated `main.go`, which doesn't exist during tests, and thus the type registry cannot be used with `ftltest` at all.

A proposed solution is to:

1. Remove the existing context-scoped code and code-generation.
2. Modify the type registry to be globally scoped.
3. Extend the `external_module.go` template to register its types in an `init()` function.

eg.

```go
func init() {
  typeregistry.Register(
    typeregistry.SumType[MySumType](*new(Variant1), *new(Variant2)),
  )
}
```

This will automatically register the module's types whenever it is imported.

**Comment by alecthomas** [comment]
We discussed this in the daily sync and there are a couple of limitations with the current approach:

1. The type registry is effectively static for the lifetime of a module's execution, but the registry is dynamically constructed and requires a `context.Context` to use.
2. Related to 1, this implies that it cannot be used by methods that don't pass a context around, including the stdlib's `encoding/json`.
3. Currently the registry is only constructed in the generated `main.go`, which doesn't exist during tests, and thus the type registry cannot be used with `ftltest` at all.

A proposed solution is to:

1. Modify the type registry to be globally scoped.
2. Extend the `external_module.go` template to register its types in an `init()` function.

eg.

```go
func init() {
  typeregistry.Register(
    typeregistry.SumType[MySumType](*new(Variant1), *new(Variant2)),
  )
}
```

This will automatically register the module's types whenever it is imported.
