### ISSUE TITLE
Module called "<name>" can not use types from another module called "<name>suffix"

### ISSUE THREAD

**Issue by matt2e** [block/ftl#1477]
- declare a module called "test"
- declare another module called "testtwo"
- declare am enum in "testtwo"
- try using the enum in "test"

**Comment by alecthomas** [comment]
Weird, is this just for enums or any type?

**Comment by matt2e** [comment]
Any I think.
The code in `schema.go` is:
```go
strings.HasPrefix(nodePath, pctx.pkg.PkgPath)
```
And I'm thinking the solution is this:
```go
func isPathInPkg(pkg *packages.Package, path string) bool {
	if path == pkg.PkgPath {
		return true
	}
	return strings.HasPrefix(path, pkg.PkgPath+"/")
}
```
