### ISSUE TITLE
Split up DAL + Controller into packages by functionality

### ISSUE THREAD

**Issue by alecthomas** [block/ftl#1567]
eg. put all lease related queries + DAL into a separate `backend/controller/leases` package along with all of the related logic

**Comment by matt2e** [comment]
@deniseli is this a dupe?

**Comment by deniseli** [comment]
reminder: update package comment on dalerrs.go

**Comment by deniseli** [comment]
Whenever we pick this back up, I'd like to split up dal.go just into separate files to start out, before we even begin the package breakdown, just to get things into a slightly more organized state first and prevent excessively-bad merge conflicts. I should have started with that all along - would have helped with anticipating what would/wouldn't work too.
