### ISSUE TITLE
Failure to connect should result into an error with `ftl deploy`

### ISSUE THREAD

**Issue by jvmakine** [block/ftl#3142]
```
> ftl deploy --endpoint=http://localhost:4678/
info:alice:build: Building module
info:alice:build: Module built (1.99s)
info:alice:deploy: Deploying module
◞[alice] 
>
```
It seems that the deploy is a success, even if there is nothing listening to port 4678.

We should give a clear error that the CLI failed to connect.

**Comment by wesbillman** [comment]
It seems like wrapped errors aren't getting reported correct when using `kctx.FatalIfErrorf(err)`

In `cli/main.go` we have this when calling `Run` on commands

```go
err = kctx.Run(ctx)
kctx.FatalIfErrorf(err)
```

If I update this to the following, I then see the messages being printed out:
```go
err = kctx.Run(ctx)
if err != nil {
	fmt.Fprintf(os.Stderr, "ftl: %+v\n", err)
	os.Exit(1)
}
```
