### ISSUE TITLE
Subscribers skip messages on module upgrade

### ISSUE THREAD

**Issue by matt2e** [block/ftl#3808]
Steps to repro:
- Have a module with a subscriber with no retry policy that is trying to get through a backlog of messages
- Deploy a newer version of the module

What goes wrong:
- The context gets cancelled which fails any active calls
- These failures are not detected any differently than other errors, and so we commit these messages as having been processed
- Then sarama closes the consumer group, which includes sending all the commits to kafka

**Comment by stuartwdouglas** [comment]
I think this is part of the more general problem of request draining.
